semver-checks: Improve new crate experience (#3464)
When we fail to find a baseline for a crate, produce a more friendly
error that tells the user what to do.

Here is an example
```
    Building bonsai-sdk v1.4.2 (current)
       Built [   7.155s] (current)
     Parsing bonsai-sdk v1.4.2 (current)
      Parsed [   0.007s] (current)
     Parsing bonsai-sdk v1.4.1 (baseline, cached)
      Parsed [   0.017s] (baseline)
    Checking bonsai-sdk v1.4.1 -> v1.4.2 (patch change)
     Checked [   0.003s] 165 checks: 165 pass, 13 skip
     Summary no semver update required
    Finished [   8.145s] bonsai-sdk

thread 'main' panicked at xtask/src/semver_checks.rs:805:13:
No SemVer baseline found for risc0-new-crate

    If this is a new crate that you intend to publish:
        - Add 'risc0-new-crate = "none"' to semver-baselines.lock

    If this is a crate that you intend to never publish:
        - Add to risc0-new-crate's Cargo.toml:
            [package.metadata.release]
            release = false
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```