Add missing env feature to clap (#2254)
With https://github.com/risc0/risc0/pull/2196 we introduced the `env`
usage in `clap` without adding the relative `env` feature to it. This
result in having issues when building `cargo-risczero`, specifically
when building it with only some of its features e.g.,:

```bash
cargo build -p cargo-risczero --no-default-features --features "cuda"
```

or

```bash
cargo build -p cargo-risczero --no-default-features --features "metal"
```

returns:

```
error[E0599]: no method named `env` found for struct `Arg` in the current scope
  --> risc0/cargo-risczero/src/commands/datasheet/mod.rs:41:38
   |
41 |     #[arg(long, value_name = "PATH", env = "RISC0_SERVER_PATH")]
   |                                      ^^^ method not found in `Arg`
```